name: Build and Release Packages

permissions:
  contents: write
  packages: write
  pull-requests: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install build-time dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ruby ruby-dev build-essential \
            tcl8.6 tk8.6 tcllib \
            libhidapi-hidraw0 libhidapi-libusb0  # Add HID libraries
          sudo gem install --no-document fpm

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller Pillow tk hid ttkbootstrap

      - name: Create desktop file
        run: |
          # Create icon directory
          mkdir -p package-files/usr/share/pixmaps
          cp bs2pro/icon.png package-files/usr/share/pixmaps/bs2pro-controller.png
          mkdir -p package-files/usr/share/applications
          cat > package-files/usr/share/applications/bs2pro-controller.desktop << EOF
          [Desktop Entry]
          Version=1.0
          Type=Application
          Name=BS2PRO Controller
          Comment=Controller for BS2PRO devices
          Exec=/usr/bin/bs2pro_controller
          Icon=system-run
          Exec=bs2pro_controller
          Icon=/usr/share/pixmaps/bs2pro-controller.png
          Categories=Utility;
          Terminal=false
          StartupNotify=false
          EOF

      - name: Build binary
        run: |
          pyinstaller --onefile --name bs2pro_controller bs2pro/main.py \
            --hidden-import=PIL._tkinter_finder \
            --hidden-import=hid \
            --hidden-import=hidapi \
            --hidden-import=ttkbootstrap \
            --collect-all hid  # Collect hidapi binaries
            --collect-all hid \
            --add-data "icon.png:." # Collect hidapi binaries

      - name: Build .deb with dependencies
        run: |
          # Create .deb with proper dependencies
          fpm -s dir -t deb -n bs2pro-controller -v "${GITHUB_REF_NAME#v}" \
            -d "libhidapi-hidraw0" \
            -d "libhidapi-libusb0" \
            -d "python3-tk" \
            --description "Controller for BS2PRO devices" \
            --url "https://github.com/lucretter/flydigibs2_linux" \
            --maintainer "Lucretter" \
            --category "utils" \
            dist/bs2pro_controller=/usr/bin/bs2pro_controller \
            package-files/usr/share/applications/bs2pro-controller.desktop=/usr/share/applications/
            package-files/usr/share/applications/bs2pro-controller.desktop=/usr/share/applications/ \
            package-files/usr/share/pixmaps/bs2pro-controller.png=/usr/share/pixmaps/bs2pro-controller.png

      - name: Build .rpm with dependencies
        run: |
          # Create .rpm with proper dependencies
          fpm -s dir -t rpm -n bs2pro-controller -v "${GITHUB_REF_NAME#v}" \
            -d "hidapi" \
            -d "python3-tkinter" \
            --description "Controller for BS2PRO devices" \
            --url "https://github.com/lucretter/flydigibs2_linux" \
            --maintainer "Lucretter" \
            --category "Applications/System" \
            dist/bs2pro_controller=/usr/bin/bs2pro_controller \
            package-files/usr/share/applications/bs2pro-controller.desktop=/usr/share/applications/
            package-files/usr/share/applications/bs2pro-controller.desktop=/usr/share/applications/ \
            package-files/usr/share/pixmaps/bs2pro-controller.png=/usr/share/pixmaps/bs2pro-controller.png

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.deb
            *.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}