name: Build and Release Packages

permissions:
  contents: write
  packages: write
  pull-requests: write

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install build-time dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ruby ruby-dev build-essential \
            libhidapi-hidraw0 libhidapi-libusb0 \
            qt6-base-dev
          sudo gem install --no-document fpm


      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel

      - name: Build Python package
        run: |
          python -m build --wheel

      - name: Create installation directory structure
        run: |
          mkdir -p package-files/opt/bs2pro-controller
          mkdir -p package-files/usr/bin
          
          # Copy the bs2pro module directly
          cp -r bs2pro/ package-files/opt/bs2pro-controller/
          
          # Install Python dependencies to the target directory
          pip install --target package-files/opt/bs2pro-controller PyQt6 hidapi Pillow --no-deps
          
          # Create wrapper script that uses system Python and Qt
          cat > package-files/usr/bin/bs2pro_controller << 'EOF'
          #!/bin/bash
          export PYTHONPATH="/opt/bs2pro-controller:$PYTHONPATH"
          exec python3 /opt/bs2pro-controller/bs2pro/main_native.py "$@"
          EOF
          chmod +x package-files/usr/bin/bs2pro_controller

      - name: Create desktop file
        run: |
          # Create icon directory
          mkdir -p package-files/usr/share/pixmaps
          cp bs2pro/icon.png package-files/usr/share/pixmaps/bs2pro-controller.png
          mkdir -p package-files/usr/share/applications
          cat > package-files/usr/share/applications/bs2pro-controller.desktop << EOF
          [Desktop Entry]
          Version=1.0
          Type=Application
          Name=BS2PRO Controller
          Comment=Controller for BS2PRO devices
          Exec=/usr/bin/bs2pro_controller
          Icon=/usr/share/pixmaps/bs2pro-controller.png
          Categories=Utility;
          Terminal=false
          StartupNotify=false
          EOF

      - name: Build .deb with dependencies
        run: |
          fpm -s dir -t deb -n bs2pro-controller -v "${GITHUB_REF_NAME#v}" \
            -d "python3" \
            -d "python3-pyqt6" \
            -d "libhidapi-hidraw0" \
            -d "libhidapi-libusb0" \
            -d "python3-tk" \
            -d "qt6-qpa-plugins" \
            -d "qt6-style-plugins | kde-style-breeze" \
            --description "Controller for BS2PRO devices with native Qt6 GUI and cross-desktop theming" \
            --url "https://github.com/lucretter/flydigibs2_linux" \
            --maintainer "Lucretter" \
            --category "utils" \
            package-files/opt/bs2pro-controller=/opt/ \
            package-files/usr/bin/bs2pro_controller=/usr/bin/ \
            package-files/usr/share/applications/bs2pro-controller.desktop=/usr/share/applications/ \
            package-files/usr/share/pixmaps/bs2pro-controller.png=/usr/share/pixmaps/

      - name: Build .rpm with dependencies
        run: |
          fpm -s dir -t rpm -n bs2pro-controller -v "${GITHUB_REF_NAME#v}" \
            -d "python3" \
            -d "python3-qt6" \
            -d "python3-hidapi" \
            -d "hidapi" \
            -d "python3-tkinter" \
            -d "qt6-qtbase" \
            -d "breeze-icon-theme" \
            --description "Controller for BS2PRO devices with native Qt6 GUI and cross-desktop theming" \
            --url "https://github.com/lucretter/flydigibs2_linux" \
            --maintainer "Lucretter" \
            --category "Applications/System" \
            package-files/opt/bs2pro-controller=/opt/ \
            package-files/usr/bin/bs2pro_controller=/usr/bin/ \
            package-files/usr/share/applications/bs2pro-controller.desktop=/usr/share/applications/ \
            package-files/usr/share/pixmaps/bs2pro-controller.png=/usr/share/pixmaps/

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.deb
            *.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
