name: Build and Release Packages

permissions:
  contents: write
  packages: write
  pull-requests: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install build‑time dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ruby ruby-dev build-essential \
            libhidapi-libusb0 libhidapi-hidraw0 \
            tcl8.6 tk8.6 tcllib   # <-- added tcllib
          sudo gem install --no-document fpm

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller Pillow tk hidapi ttkbootstrap

      - name: Build binary (using spec if you bundled msgcat)
        run: |
          pyinstaller --onefile --name bs2pro_controller bs2pro/main.py \
            --hidden-import=PIL._tkinter_finder \
            --hidden-import=hid \
            --hidden-import=hidapi \
            --hidden-import=ttkbootstrap

      - name: Build .deb and .rpm
        run: |
          # Build .deb package with dependencies + udev rule
          fpm -s dir -t deb -n bs2pro_controller -v "${GITHUB_REF_NAME}" \
              --deb-no-default-config-files \
              --depends "libhidapi-libusb0" \
              --depends "libhidapi-hidraw0" \
              --depends "libusb-1.0-0" \
              dist/bs2pro_controller=/usr/bin/bs2pro_controller \

          # Build .rpm package with dependencies + udev rule
          fpm -s dir -t rpm -n bs2pro_controller -v "${GITHUB_REF_NAME}" \
              --depends "hidapi" \
              --depends "libusb1" \
              dist/bs2pro_controller=/usr/bin/bs2pro_controller \

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.deb
            *.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
