name: Build and Release Packages

permissions:
  contents: write
  packages: write
  pull-requests: write

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install build-time dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ruby ruby-dev build-essential \
            libhidapi-hidraw0 libhidapi-libusb0
          sudo gem install --no-document fpm


      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller hidapi customtkinter PyQt6

      - name: Create desktop file
        run: |
          # Create icon directory
          mkdir -p package-files/usr/share/pixmaps
          cp bs2pro/icon.png package-files/usr/share/pixmaps/bs2pro-controller.png
          mkdir -p package-files/usr/share/applications
          cat > package-files/usr/share/applications/bs2pro-controller.desktop << EOF
          [Desktop Entry]
          Version=1.0
          Type=Application
          Name=BS2PRO Controller
          Comment=Controller for BS2PRO devices
          Exec=/usr/bin/bs2pro_controller
          Icon=/usr/share/pixmaps/bs2pro-controller.png
          Categories=Utility;
          Terminal=false
          StartupNotify=false
          EOF

      - name: Build binary
        run: |
          # Build PyInstaller command with conditional binary inclusion
          PYINSTALLER_CMD="pyinstaller --onefile --name bs2pro_controller \
            --add-data 'bs2pro/icon.png:.' \
            --add-data 'bs2pro/controller.py:.' \
            --add-data 'bs2pro/config.py:.' \
            --add-data 'bs2pro/gui.py:.' \
            --add-data 'bs2pro/qt_tray_manager.py:.' \
            --add-data 'bs2pro/udev_manager.py:.' \
            --add-data 'bs2pro/cpu_monitor.py:.' \
            --add-data 'bs2pro/smart_mode.py:.' \
            --add-data 'bs2pro/rpm_monitor.py:.' \
            --hidden-import=hidapi \
            --hidden-import=hid \
            --hidden-import=hidapi.hidapi \
            --hidden-import=customtkinter \
            --hidden-import=PyQt6 \
            --hidden-import=PyQt6.QtCore \
            --hidden-import=PyQt6.QtGui \
            --hidden-import=PyQt6.QtWidgets \
            --hidden-import=rpm_monitor \
            --hidden-import=bs2pro.rpm_monitor \
            --hidden-import=bs2pro.controller \
            --hidden-import=bs2pro.gui \
            --hidden-import=bs2pro.config \
            --hidden-import=bs2pro.qt_tray_manager \
            --hidden-import=bs2pro.udev_manager \
            --hidden-import=bs2pro.cpu_monitor \
            --hidden-import=bs2pro.smart_mode \
            --collect-all=hidapi \
            --collect-data=hidapi \
            --collect-submodules=hidapi \
            --collect-all=customtkinter \
            --collect-data=customtkinter \
            --collect-all=PyQt6 \
            --collect-all=bs2pro"
          
          # Add HID library binaries if they exist
          if [ -f "/usr/lib/x86_64-linux-gnu/libhidapi-hidraw.so.0" ]; then
            PYINSTALLER_CMD="$PYINSTALLER_CMD --add-binary '/usr/lib/x86_64-linux-gnu/libhidapi-hidraw.so.0:.'"
          fi
          
          if [ -f "/usr/lib/x86_64-linux-gnu/libhidapi-libusb.so.0" ]; then
            PYINSTALLER_CMD="$PYINSTALLER_CMD --add-binary '/usr/lib/x86_64-linux-gnu/libhidapi-libusb.so.0:.'"
          fi
          
          # Add the main script and execute
          PYINSTALLER_CMD="$PYINSTALLER_CMD bs2pro/main.py"
          
          echo "Running: $PYINSTALLER_CMD"
          eval $PYINSTALLER_CMD

      - name: Build .deb with dependencies
        run: |
          fpm -s dir -t deb -n bs2pro-controller -v "${GITHUB_REF_NAME#v}" \
            -d "libhidapi-hidraw0" \
            -d "libhidapi-libusb0" \
            -d "python3-tk" \
            -d "python3-pyqt6" \
            --description "Controller for BS2PRO devices with system tray support" \
            --url "https://github.com/lucretter/flydigibs2_linux" \
            --maintainer "Lucretter" \
            --category "utils" \
            dist/bs2pro_controller=/usr/bin/bs2pro_controller \
            package-files/usr/share/applications/bs2pro-controller.desktop=/usr/share/applications/ \
            package-files/usr/share/pixmaps/bs2pro-controller.png=/usr/share/pixmaps/bs2pro-controller.png

      - name: Build .rpm with dependencies
        run: |
          fpm -s dir -t rpm -n bs2pro-controller -v "${GITHUB_REF_NAME#v}" \
            -d "hidapi" \
            -d "python3-tkinter" \
            -d "python3-qt6" \
            --description "Controller for BS2PRO devices with system tray support" \
            --url "https://github.com/lucretter/flydigibs2_linux" \
            --maintainer "Lucretter" \
            --category "Applications/System" \
            dist/bs2pro_controller=/usr/bin/bs2pro_controller \
            package-files/usr/share/applications/bs2pro-controller.desktop=/usr/share/applications/ \
            package-files/usr/share/pixmaps/bs2pro-controller.png=/usr/share/pixmaps/bs2pro-controller.png

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.deb
            *.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
